### ISSUE TITLE
cloud分支: mock-server启动报错TypeError: router[method] is not a function

### ISSUE THREAD

**Issue by existenceO** [imageslr/taro-library#8]
```
simplest-mock-server> gulp mock
[23:53:07] Using gulpfile \taro-library-cloud\simplest-mock-server\gulpfile.js
[23:53:07] Starting 'mock'...
[23:53:07] Finished 'mock' after 51 ms
[23:53:07] [nodemon] 2.0.7
[23:53:07] [nodemon] to restart at any time, enter `rs`
[23:53:07] [nodemon] watching path(s): example\**\* server.js router.js
[23:53:07] [nodemon] watching extensions: js,json
[23:53:07] [nodemon] starting `node ./server.js --dir example --port 3000`
[INFO] Reading mock template file: \taro-library-cloud\simplest-mock-server\example\GET\books\hot.json
[INFO] Reading mock template file: \taro-library-cloud\simplest-mock-server\example\GET\books\isbn\{isbn}.json
[INFO] Reading mock template file: \taro-library-cloud\simplest-mock-server\example\GET\books\new.json
[INFO] Reading mock template file: \taro-library-cloud\simplest-mock-server\example\GET\books\recommend.json
[INFO] Reading mock template file: \taro-library-cloud\simplest-mock-server\example\GET\books\{id}.json
[INFO] Reading mock template file: \taro-library-cloud\simplest-mock-server\example\GET\books.json
\taro-library-cloud\simplest-mock-server\router.js:69
  router[method](pathname, handler);
                ^

TypeError: router[method] is not a function
    at routes.forEach (D:\taro-library-cloud\simplest-mock-server\router.js:69:17)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\programs\demo\taro-library-cloud\simplest-mock-server\router.js:50:8)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
application has crashed!
```
请问下这个是缺少了什么依赖么？node: v11.8.0，已执行npm install 
(PS:按12版本去安装，也报错：fs.js:45 } = primordials； ^ ReferenceError: primordials is not defined ，网上给出的答案是node12版本不支持gulp4以下版本)
QAQ，求解惑

**Comment by imageslr** [comment]
cloud 分支需要升级 node 版本。试试 node：v12.22.1 吧。
