### ISSUE TITLE
gulp mock 报错

### ISSUE THREAD

**Issue by gllzqfe** [imageslr/taro-library#9]
C:\Users\goul\taro-library\simplest-mock-server>gulp mock
[20:59:51] Using gulpfile ~\taro-library\simplest-mock-server\gulpfile.js
[20:59:51] Starting 'mock'...
[20:59:52] Finished 'mock' after 758 ms
[20:59:52] [nodemon] 2.0.7
[20:59:52] [nodemon] to restart at any time, enter `rs`
[20:59:52] [nodemon] watching path(s): example\**\* server.js router.js
[20:59:52] [nodemon] watching extensions: js,json
[20:59:52] [nodemon] starting `node ./server.js --dir example --port 3000`
[INFO] Reading mock template file: C:\Users\goul\taro-library\simplest-mock-server\example\GET\books\hot.json
[INFO] Reading mock template file: C:\Users\goul\taro-library\simplest-mock-server\example\GET\books\isbn\{isbn}.json
[INFO] Reading mock template file: C:\Users\goul\taro-library\simplest-mock-server\example\GET\books\new.json
[INFO] Reading mock template file: C:\Users\goul\taro-library\simplest-mock-server\example\GET\books\recommend.json
[INFO] Reading mock template file: C:\Users\goul\taro-library\simplest-mock-server\example\GET\books\{id}.json
[INFO] Reading mock template file: C:\Users\goul\taro-library\simplest-mock-server\example\GET\books.json
C:\Users\goul\taro-library\simplest-mock-server\router.js:69
  router[method](pathname, handler);
                ^

TypeError: router[method] is not a function
    at routes.forEach (C:\Users\goul\taro-library\simplest-mock-server\router.js:69:17)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\goul\taro-library\simplest-mock-server\router.js:50:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
application has crashed!

[20:59:54] [nodemon] app crashed - waiting for file changes before starting...

请问这是什么原因，我是用的windows 11的环境，cmd窗口执行gulp mock报错

**Comment by gllzqfe** [comment]
<img width="647" alt="微信图片_20241125211200" src="https://github.com/user-attachments/assets/3c1f34d2-c32c-42f6-8366-2f76586a5488">
69行并没有看出来有什么问题，请指教
